fix(features): use correct feature pk for SIMD-0083 (#1246)
Fixes a bug where we had the wrong feature pubkey in `features.zon` for
SIMD-0083. This was causing a slothash mismatch, preventing replay from
progressing.

```bash  
$ solana --version
solana-cli 3.1.8 (src:2717084a; feat:1620780344, client:Agave)
$ solana feature status -ut 4WeHX6QoXCCwqbSFgi6dxnB6QsPo6YApaNTH7P4MLQ99 
Feature                                      | Status                  | Activation Slot | Description
4WeHX6QoXCCwqbSFgi6dxnB6QsPo6YApaNTH7P4MLQ99 | active since epoch 915  | 389756256       | SIMD-0083: Allow batched transactions to read/write and write/write the same accounts
```

vs what we had: 

```sh
$ solana feature status -ut ENTRYnPAoT5Swwx73YDGzMp3XnNH1kxacyvLosRHza1i
Error: Bad parameter: Unknown feature: ENTRYnPAoT5Swwx73YDGzMp3XnNH1kxacyvLosRHza1i
```

See:
https://github.com/anza-xyz/agave/blob/2717084afeeb7baad4342468c27f528ef617a3cf/feature-set/src/lib.rs#L1082