fix(build): `zig build` fails due to some exes not using llvm (#1450)
Whenever I run `zig build` on my linux desktop, it crashes:

```
error: fatal linker error: unhandled relocation type R_X86_64_PC64 at offset 0x1c
    note: in /usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/../../../../lib/crt1.o:.sframe
error: fatal linker error: unhandled relocation type R_X86_64_PC64 at offset 0x2c
    note: in /usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/../../../../lib/crt1.o:.sframe
```

`zig build sig` and `zig build test` have no such problem. Also using
ReleaseSafe avoids the issue.

The problem is that the self-hosted x86 backend is used for many of the
exes. We just need to use llvm for these, like the other targets. They
now all respect the `-Duse-llvm` option.