fix: incremental compilation (#781)
### Problem
Incremental compilation doesn't work for sig because one of our
dependencies (libxev) uses the `usingnamespace` keyword.

### Fix
I forked libxev and removed usingnamespace here:
https://github.com/dnut/libxev and switched to that as sig's dependency.

### Verify
Run `zig build -fincremental`. It panics on main with this error:

> error: thread 3490520122 panic: 'usingnamespace' is not supported by
incremental compilation

It runs without error on this branch.