fix(replay): skip slot_frozen event when parent is pruned (#1500)
# Intent

- Prevent websocket event emitting codepath from taking down validator
```
time=2026-05-29T15:26:38.944Z level=info scope=replay_tower message="Can vote on: 411729832 96.2%"
time=2026-05-29T15:26:38.944Z level=info scope=replay_tower message="recorded vote in tower for slot 411729832, new root: 411729800"
time=2026-05-29T15:26:38.944Z level=info scope=fork_choice message="fork_choice: new root set to slot=411729800 hash=6epcrZGTe1wbuwa9NSkShJxVM5gzmeqxZWvusK5pX1PK"
time=2026-05-29T15:26:38.952Z level=info scope=replay message="slot state update from consensus: .{ .root = 411729800, .voted = 411729832, .optimistically_confirmed = null }"
time=2026-05-29T15:26:38.952Z level=info scope=replay message="Commitments" processed=411729832  confirmed=411729831  finalized=411729793  behind=0 
time=2026-05-29T15:26:38.952Z level=info scope=replay message="advanced in 62.455ms"
time=2026-05-29T15:26:38.953Z level=info scope=replay message="tracking new slot: 411729833"
time=2026-05-29T15:26:39.086Z level=info scope=replay message="3 active slots to replay: { 411729818, 411729796, 411729833 }"
time=2026-05-29T15:26:39.086Z level=info scope=replay message="slot is dead: 411729818"
time=2026-05-29T15:26:39.086Z level=info scope=replay message="got 4 entries for slot 411729796"
time=2026-05-29T15:26:39.086Z level=info scope=replay message="got 33 entries for slot 411729833"
time=2026-05-29T15:26:39.098Z level=info scope=replay message="finished replaying slot: 411729796"
time=2026-05-29T15:26:39.107Z level=info scope=replay.freeze message="froze slot 411729796 with hash 2TWjvWdJrFpQWJvyDKxGPKYYdZXTZLDg7cVHFWEYXuZg"
time=2026-05-29T15:26:39.107Z level=info scope=replay message="partially replayed slot: 411729833"
error: MissingParent
time=2026-05-29T15:26:39.107Z level=error scope=service_manager message="replay has errored: error.MissingParent null"
time=2026-05-29T15:26:39.107Z level=error scope=service_manager message="Signaling exit due to 1 errors from replay"
```

# Implementation

- Replaced `error.MissingParent` return with a break to skip event block

# Ramifications

- This isn't currently an issue but at the head of the chain this could
occur under the right conditions

# Tests

- Add regression test verifying no crash and no spurious event