fix(build.zig): ssh.getHostTarget json->zon (#792)
This fixes two bugs in build.zig's ssh code for interacting with remote
hosts and improves the readability of the code and the help message.

# Problem 1 - Parsing Failure
### Observation
```
$ zig build -Dssh-host=myserver -Doptimize=ReleaseSafe sig

thread 409278 panic: error.SyntaxError

std/json/scanner.zig:746:33: 0x1608eeb in next (build)
                        else => return error.SyntaxError,
                                ^
...
```

### Cause
`ssh.getHostTarget` in `build.zig` was written for zig 0.13 which
outputs `zig targets` in json. Since upgrading to 0.14.1, `zig targets`
now outputs in zon, which fails to be parsed by `std.json`.

### Fix
I updated the parsing logic in build.zig to parse the output as zon.

# Problem 2 - Wrong Path

### Observation
```
$ zig build -Dssh-host=myserver -Doptimize=ReleaseSafe sig -- validator -c testnet

/usr/bin/rsync
sig
    204,409,176 100%   22.94MB/s    0:00:08 (xfr#1, to-chk=0/1)
bash: line 1: zig-out/bin//sig: No such file or directory
Connection to 13.58.101.100 closed.
sig
└─ run ssh failure
error: the following command exited with error code 127:
ssh -t myserver cd sig; zig-out/bin//sig validator -c testnet 
Build Summary: 30/32 steps succeeded; 1 failed
sig transitive failure
└─ run ssh failure
```

### Cause
The file was being copied into the wrong folder in the remote host. This
was introduced in #760 where the path on the remote host was edited to
use `local_path` instead of the filename.

The entire directory structure of the local host was being duplicated
within the bin folder on the remote host. So sig was being copied to
`/home/ubuntu/sig/zig-out/bin/Users/drew/sig/zig-out/bin/sig` instead of
/home/ubuntu/sig/zig-out/bin/sig`, so it failed to be executed when the
build script later tried to run it from that path.

### Fix

I changed back the `local_path` portion of the remote path to the
binary's filename, which is specified with `install.dest_sub_path`.